---
- name: nginx-install
  hosts: unangtarget
  become: true

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Start nginx service
      service:
        name: nginx
        state: started
